spring:
  rabbitmq:
    host: 47.92.173.234
    port: 5672
    username: guest
    password: guest

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/shopping?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    initialization-mode: always
    #    schema:
    #      - classpath:sql/user.sql
    #      - classpath:sql/employee.sql
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.hkbu.commerce.entity
